### ISSUE TITLE
"Getting Started" example not working as expected

### ISSUE THREAD

**Issue by ehinderer** [bmeg/grip#267]
I'm trying to explore the graph with some example queries and the example given [here](https://bmeg.github.io/grip/docs/queries/getting_started/) is not working for me. I'm getting the following error after running 

> result = G.query().V().hasLabel("Gene").has(gripql.eq("symbol","TP53")).execute()

[ERROR]	2021-11-15 09:29:30,729	Failed to decode: b'\<html\>'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/gripql/query.py", line 367, in execute
    for r in self.__stream(raw=raw, debug=debug):
  File "/usr/local/lib/python3.9/site-packages/gripql/query.py", line 323, in __stream
    raise e
  File "/usr/local/lib/python3.9/site-packages/gripql/query.py", line 320, in __stream
    result_dict = jloads(result.decode())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kellrott** [comment]
That page needs to be updated. The system now have authentication, see the access info at: https://bmeg.io/analyze/access
